### PR TITLE
Fix non-streaming respond() does not add .response() entry to transcript

### LINKED ISSUE #45: Non-streaming respond() does not add .response() entry to transcript
When using `session.respond()` (non-streaming), the transcript only contains `.prompt()` entries but no `.response()` entries for the model's text output. 

### Expected Behavior
The transcript should contain both `.prompt()` and `.response()` entries after each interaction, similar to how streaming works.

### Actual Behavior
The transcript only contains `.prompt()` entries. The model's response text exists in `response.content` but is never added to the transcript as a `.response()` entry.

### PR DESCRIPTION
**Pull request by noorbhatia**
Fix #45

### CODE REVIEW

File: Tests/AnyLanguageModelTests/MockLanguageModelTests.swift [hunk 1]
```diff
@@ -13,9 +13,8 @@ struct MockLanguageModelTests {
         let response = try await session.respond(to: "Say hello")
         #expect(response.content == "Hello, World!")
 
-        // Verify transcript was updated
+        // Verify transcript was updated (prompt + response)
         #expect(session.transcript.count == 2)
-        #expect(response.transcriptEntries.count > 0)
```
Comment (noorbhatia) [inline Tests/AnyLanguageModelTests/MockLanguageModelTests.swift:18]: Both assertions that checked `response.transcriptEntries.count > 0` have been removed since:

- `transcriptEntries` only contains tool-related entries (empty when no tools are used)
- The `.response()` entry is now added to `session.transcript` by the session, not returned in `response.transcriptEntries`

File: Tests/AnyLanguageModelTests/Shared/MockLanguageModel.swift [hunk 2]
```diff
@@ -36,17 +36,10 @@ struct MockLanguageModel: LanguageModel {
         let promptWithInstructions = Prompt("Instructions: \(session.instructions?.description ?? "N/A")\n\(prompt)")
         let text = try await responseProvider(promptWithInstructions, options)
 
-        let responseEntry = Transcript.Entry.response(
-            Transcript.Response(
-                assetIDs: [],
-                segments: [.text(.init(content: text))]
-            )
-        )
-
```
Comment (noorbhatia) [inline Tests/AnyLanguageModelTests/Shared/MockLanguageModel.swift:45]: The mock was returning a `responseEntry` in `transcriptEntries`, which was working around the session bug. Now that the session is fixed, the mock should follow the same pattern as real models.

Comment (mattt) [reply Tests/AnyLanguageModelTests/Shared/MockLanguageModel.swift:45]: 😅 Whoops. Nice catch!
